### ISSUE TITLE
publishable key passed as a query params makes invalid request

### ISSUE THREAD

**Issue by cfabianski** [Bearer/bug-tracker#1]
```{"error":{"code":"parameter_unknown","doc_url":"https://stripe.com/docs/error-codes/parameter-unknown","message":"Received unknown parameter: clientId","param":"clientId","type":"invalid_request_error"}}``` while using Bearer/JS

**Comment by cfabianski** [comment]
https://github.com/Bearer/bearer/issues/731

**Comment by cfabianski** [comment]
https://github.com/Bearer/integration-service/pull/459

**Comment by tanguyantoine** [comment]
solved
