### ISSUE TITLE
Increase request timeout to 30 seconds

### ISSUE THREAD

**Issue by elsapet** [Bearer/bug-tracker#3]
## Description

Some APIs are taking longer than our current default timeout (6 seconds). We would like to allow Bearer users to make longer requests (up to 30 seconds). We'll need to update our infrastructure and our clients to support timeouts greater than the current default.

## Actions

- [x] Increase timeout on infrastructure
- [x] Update client to support timeout options (default to 5 seconds)
- [x] Update documentation regarding timeouts

**Comment by RadekMolenda** [comment]
This ticket is now done!
